name: prueba2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5   # ✅ Necesario para el componente Link
  flutter_svg: ^2.0.7  # o la última estable

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
    
  assets:
    - assets/icons/
